<?php
require __DIR__.'/auth.php';require __DIR__.'/../artwork-common.php';
$filter=strtolower((string)($_GET['status']??'all'));
if(!in_array($filter,['all','pending','approved','rejected'],true))$filter='all';
$sql='SELECT a.artwork_id,a.title,a.description,a.status,a.created_at,a.rejection_reason,u.FULL_NAME AS artist,c.category_name,(SELECT image_path FROM artwork_images WHERE artwork_id=a.artwork_id ORDER BY image_id LIMIT 1) AS image_path FROM artworks a JOIN users u ON a.user_id=u.USER_ID JOIN categories c ON c.category_id=a.category_id';
if($filter!=='all'){$sql.=' WHERE LOWER(a.status)=?';}$sql.=' ORDER BY a.created_at DESC,a.artwork_id DESC LIMIT 100';
if($filter==='all')$rows=$conn->query($sql);else{$stmt=$conn->prepare($sql);$stmt->bind_param('s',$filter);$stmt->execute();$rows=$stmt->get_result();}
$message=['approved'=>'Artwork approved.','rejected'=>'Artwork rejected.','error'=>'Could not update artwork.','featured'=>'Featured artwork updated.'][$_GET['msg']??'']??null;
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Artwork Reviews | MIRA Admin</title><script>try{document.documentElement.dataset.theme=localStorage.getItem('mira-theme')==='dark'?'dark':'light'}catch(e){document.documentElement.dataset.theme='light'}</script><link rel="stylesheet" href="admin.css"><link rel="stylesheet" href="../artwork-workflow.css"><script defer src="admin.js"></script></head><body class="admin-page"><div class="admin-layout"><aside class="admin-sidebar"><a href="dashboard.php" class="admin-brand"><span class="brand-symbol">✦</span><span class="brand-copy">MIRA <small>ADMIN STUDIO</small></span></a><nav class="admin-nav"><a href="dashboard.php">▦ Dashboard</a><a href="artworks.php" class="active" aria-current="page">▤ Artwork reviews</a><span class="admin-nav-disabled">◈ Categories <small>Soon</small></span><span class="admin-nav-disabled">▣ Exhibitions <small>Soon</small></span><span class="admin-nav-disabled">▥ Reports <small>Soon</small></span></nav><div class="admin-user-box"><div class="admin-user"><span class="admin-avatar">✦</span><div><strong><?= h($adminName) ?></strong><span>Administrator</span></div></div><form method="post" action="logout.php"><button class="logout-button">Log out</button></form></div></aside><main class="admin-main"><header class="admin-topbar"><p class="admin-breadcrumb">MIRA / <strong>Artwork Reviews</strong></p><button id="themeToggle" class="admin-theme-toggle" type="button">☾ Dark mode</button></header><section class="admin-hero"><p class="admin-hero-label">CURATE STUDENT CREATIVITY</p><h1>Artwork submissions <span>✦</span></h1><p>Review, approve, reject and feature student artworks.</p></section>
<?php if($message): ?><p class="notice <?=($_GET['msg']==='error'?'error':'success')?>" role="status"><?= h($message) ?></p><?php endif; ?>
<div class="filter-pills"><?php foreach(['all'=>'All','pending'=>'Pending','approved'=>'Approved','rejected'=>'Rejected'] as $key=>$label): ?><a href="?status=<?= $key ?>" class="filter-pill <?= $filter===$key?'selected':'' ?>"><?= h($label) ?></a><?php endforeach; ?></div>
<section class="review-grid"><?php if(!$rows||!$rows->num_rows): ?><article class="admin-panel">No <?= h($filter==='all'?'':$filter) ?> artworks found.</article><?php endif; ?>
<?php if($rows):while($a=$rows->fetch_assoc()):$status=strtolower($a['status']);?><article class="review-card"><div class="review-image"><?php if($a['image_path']):?><img src="../<?= h($a['image_path']) ?>" alt="<?= h($a['title']) ?>" loading="lazy"><?php else:?><div>No image</div><?php endif;?></div><div class="review-content"><span class="state state-<?= in_array($status,['pending','approved','rejected'],true)?$status:'pending' ?>"><?= h(ucfirst($status)) ?></span><h2><?= h($a['title']) ?></h2><p><?= h($a['artist']) ?> · <?= h($a['category_name']) ?></p><p class="review-description"><?= nl2br(h($a['description'])) ?></p><?php if($status==='rejected' && $a['rejection_reason']):?><p class="rejection">Reason: <?= h($a['rejection_reason']) ?></p><?php endif; ?>
<?php if($status==='pending'):?><form class="review-form" method="post" action="review-artwork.php"><input type="hidden" name="csrf" value="<?= h(artworkCsrf()) ?>"><input type="hidden" name="artwork_id" value="<?= (int)$a['artwork_id'] ?>"><label for="reason-<?= (int)$a['artwork_id'] ?>">Rejection reason (required when rejecting)</label><textarea name="reason" id="reason-<?= (int)$a['artwork_id'] ?>" maxlength="1000" rows="2" placeholder="Explain why the artwork cannot be approved..."></textarea><div class="review-buttons"><button class="primary-btn" name="decision" value="approved" type="submit">✓ Approve</button><button class="outline-btn" name="decision" value="rejected" type="submit">✕ Reject</button></div></form><?php endif; ?>
<?php if($status==='approved'): ?><form method="post" action="review-artwork.php"><input type="hidden" name="csrf" value="<?= h(artworkCsrf()) ?>"><input type="hidden" name="artwork_id" value="<?= (int)$a['artwork_id'] ?>"><button class="outline-btn" name="decision" value="toggle_featured" type="submit">✧ Toggle homepage feature</button></form><?php endif; ?></div></article><?php endwhile;endif; ?></section>
</main></div></body></html>
